name: Tests

on: [push, pull_request]

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  build:
    name: Install, Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [12, 14, 15]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node }}
      - name: Cache pnpm modules
        uses: actions/cache@v2
        env:
          cache-name: cache-pnpm-modules
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node }}-

      - uses: pnpm/action-setup@v1.2.1
        with:
          version: latest
          run_install: false
      - name: Node version
        run: node --version
      - name: pnpm version
        run: pnpm --version
      - name: Install dependencies and build
        run: pnpm install
      - name: Test everything
        run: pnpm test
